const styles = {
  container: {
    marginTop: '15px',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  box_title: {
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    alignItems: 'center',
    bgcolor: 'white',
    color: '#030104',
    borderRadius: '1em',
    border: 'solid #030104 3px',
    boxShadow: '0px 0px 20px 2px rgba(54,54,54,0.75)',
    height: '100%',
    width: '80%',
    p: 1,
    marginBottom: '20px',
  },
  box_information: {
    display: 'flex',
    alignItems: 'center',
    bgcolor: '#96a42f',
    borderRadius: '1em',
    boxShadow: '0px 0px 20px 2px rgba(54,54,54,0.75)',
    height: '100%',
    width: '80%',
    p: 3,
    marginBottom: '20px',
  },
  github: {
    backgroundColor: '#b4d241',
    borderRadius: '1em',
    mb: 4,
    mt: 2,
    p: 4,
    width: '80vw',
  },
  box_cards: {
    display: 'flex',
    justifyContent: 'space-around',
    width: '100%',
    pt: 2,
    marginBottom: '20px',
  },
  typography: {
    fontWeight: '500',
  },
};

export default styles;
